### ISSUE TITLE
Integrate `shellcheck` to CI

### ISSUE THREAD

**Issue by dylanaraps** [themix-project/oomoxify#1]
I took a quick peek at the files and they're rather unsafe. You should run `shellcheck` on the scripts and fix the unsafe commands and various pitfalls found throughout.

**For example:**

```sh
rm "${tmp_dir}/"* -r
```

What happens if `$tmp_dir` is unset? Well, `rm` will recursively try to delete everything under `/*`. See why this is *really* bad?

**Another example:**

```sh
THEME=$(basename ${THEME})
```

What happens if `$THEME` contains one or more whitespace characters? Bash will split the var at every whitespace character and `basename` will be given multiple incomplete file paths causing the script to just fail.

All you need to do is properly quote your vars. This happens dozens of times throughout the script.

**Another example:**

```sh
for file in $(ls "${backup_dir}"/*.spa) ; do
```

You should never parse the output of `ls` nor do you need to. This line could be simplified to just:

```sh
for file in "$backup_dir"/*.spa; do
```

I'll stop there but this should give you an idea of why these changes need to be made. Run shellcheck and you'll see the large number of changes that need to be made.

**Comment by actionless** [comment]
1) >What happens if $tmp_dir is unset?

have you heard of `set -u`?
i've actually even installed `shellcheck` and it seems it's not taking `set` into account as well during the analysis

2) thanks for this one, i remember fixing similar set of  issues once when somebody reported what can't generate themes with specific names but i guess i've added/edited those lines after those fixes :-D

3) thanks, that left from the time when i was doing some extra filtering of filelist through the pipe, so indeed not needed by now

as a general outcome, i would thank you once again and i think it makes sense to add shellcheck to travis but before that to configure it to ignore some specific checks: when i was running it now it shown quite a lot of other false-positive cases

**Comment by actionless** [comment]
i've updated the script but still was too lazy to prepare travis with shellcheck

**Comment by actionless** [comment]
done: https://travis-ci.org/themix-project/oomoxify/builds/473120590

thanks for reporting!
